serviceAccount:
  create: false
  name: ${service_account_name}

resources:
  limits:
    cpu: 1
    memory: 1000Mi
  requests:
    cpu: 100m
    memory: 100Mi

nodeSelector:
  kubernetes.io/os: linux
